name: resumecorgi.com

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'

      - name: Restore Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  build:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'

      - name: Restore Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

  deploy-cloudflare:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [ build, validate ]
    runs-on: ubuntu-latest
    name: Deploy (Cloudflare)
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=resumecorgi
